### ISSUE TITLE
How to extract properties / attributes?

### ISSUE THREAD

**Issue by bskade** [spinico/vue-gettext-cli#2]
like 
```
<input :placeholder="'Email address' | translate" />
<input :placeholder="$gettext('Email address')" />
```
both will not be extracted

**Comment by spinico** [comment]
Interpolation within attributes has been [deprecated in Vue 2](https://vuejs.org/v2/guide/migration.html#Interpolation-within-Attributes-removed).

A workaround is to specify custom start and end delimiters on the extract command and use a computed value, for example:

```
<template>
   <input :placeholder="EMAIL_ADDRESS | translate" />
</template>

<script>
import Vue from 'vue'

export default {
  name: 'HelloWorld',
  computed: {
    EMAIL_ADDRESS () {
      return this.$gettext('EMAIL_ADDRESS')
    }
  }
}
</script>
```
And with the extract command :

vue-gettext-cli extract --startDelimiter '' --endDelimiter '' --locales en fr

**Comment by spinico** [comment]
Another approach is to define a custom filter. 

For example:

```
<template>
   <input :placeholder="'EMAIL_ADDRESS' | translate" />
</template>

<script>
import Vue from 'vue'

Vue.filter('translate', value => {
  return !value
    ? ''
    : Vue.prototype.$gettext(value.toString())
})

</script>
```
